"""simplify notification_preference scheduling

Revision ID: 218ace419d49
Revises: 3f9662f4f468
Create Date: 2026-08-02 02:04:25.399702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '218ace419d49'
down_revision: Union[str, Sequence[str], None] = '3f9662f4f468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferences', sa.Column('next_run_at', sa.Date(), nullable=True))
    op.drop_index(op.f('ix_notification_preferences_next_send_at'), table_name='notification_preferences')
    op.create_index(op.f('ix_notification_preferences_next_run_at'), 'notification_preferences', ['next_run_at'], unique=False)
    op.drop_column('notification_preferences', 'timezone')
    op.drop_column('notification_preferences', 'frequency')
    op.drop_column('notification_preferences', 'send_hour_utc')
    op.drop_column('notification_preferences', 'next_send_at')
    # ### end Alembic commands ###

    # digest_frequency's only column just got dropped; DROP COLUMN doesn't
    # drop the Postgres ENUM type itself (same gotcha as the initial
    # migration), so clean it up explicitly.
    op.execute("DROP TYPE IF EXISTS digest_frequency")


def downgrade() -> None:
    """Downgrade schema."""
    # recreate the type upgrade() dropped, before any column can reference it
    op.execute("CREATE TYPE digest_frequency AS ENUM ('DAILY', 'WEEKLY')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferences', sa.Column('next_send_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('notification_preferences', sa.Column('send_hour_utc', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('frequency', postgresql.ENUM('DAILY', 'WEEKLY', name='digest_frequency'), autoincrement=False, nullable=False))
    op.add_column('notification_preferences', sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_notification_preferences_next_run_at'), table_name='notification_preferences')
    op.create_index(op.f('ix_notification_preferences_next_send_at'), 'notification_preferences', ['next_send_at'], unique=False)
    op.drop_column('notification_preferences', 'next_run_at')
    # ### end Alembic commands ###
