"""add territory options, category subscriptions, do not contact, exclusivity, rank score

Revision ID: 1e1c82ae7136
Revises: 218ace419d49
Create Date: 2026-08-02 02:42:19.194054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1e1c82ae7136'
down_revision: Union[str, Sequence[str], None] = '218ace419d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('territory_options',
    sa.Column('source_city', sa.String(), nullable=False),
    sa.Column('kind', postgresql.ENUM('ZIP', 'BOROUGH', 'LOCAL_AUTHORITY', 'RADIUS', name='territory_kind', create_type=False), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_city', 'kind', 'value', name='uq_territory_option')
    )
    op.create_index(op.f('ix_territory_options_source_city'), 'territory_options', ['source_city'], unique=False)
    op.create_table('category_subscriptions',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('category', postgresql.ENUM('PEST', 'SANITATION', 'EQUIPMENT', 'PLUMBING', 'TEMPERATURE', 'OTHER', name='violation_category', create_type=False), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'category', name='uq_client_category')
    )
    op.create_table('do_not_contact',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('source_city', sa.String(), nullable=False),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'source_city', 'license_number', name='uq_do_not_contact')
    )
    op.add_column('client_leads', sa.Column('rank_score', sa.Numeric(), nullable=True))
    # server_default backfills existing rows (clients table is not empty);
    # the model only declares a Python-side default, which is fine for new
    # rows going forward but can't satisfy NOT NULL on rows that already exist.
    op.add_column(
        'clients', sa.Column('is_exclusive', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'is_exclusive')
    op.drop_column('client_leads', 'rank_score')
    op.drop_table('do_not_contact')
    op.drop_table('category_subscriptions')
    op.drop_index(op.f('ix_territory_options_source_city'), table_name='territory_options')
    op.drop_table('territory_options')
    # ### end Alembic commands ###
