"""add zip mapping flags

Revision ID: 7dbddf5666ae
Revises: f44939c5befc
Create Date: 2026-08-02 15:12:16.510744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dbddf5666ae'
down_revision: Union[str, Sequence[str], None] = 'f44939c5befc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zip_mapping_flags',
    sa.Column('inspection_event_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspection_event_id'], ['inspection_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zip_mapping_flags_inspection_event_id'), 'zip_mapping_flags', ['inspection_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zip_mapping_flags_inspection_event_id'), table_name='zip_mapping_flags')
    op.drop_table('zip_mapping_flags')
    # ### end Alembic commands ###
