"""add inspection_events narration column

Revision ID: c74e81799494
Revises: 1e1c82ae7136
Create Date: 2026-08-02 03:30:32.162089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c74e81799494'
down_revision: Union[str, Sequence[str], None] = '1e1c82ae7136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspection_events', sa.Column('narration', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspection_events', 'narration')
    # ### end Alembic commands ###
